services:
  - type: web
    name: open-stitch
    runtime: docker
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_CLERK_PUBLISHABLE_KEY
        sync: false
      - key: CLERK_SECRET_KEY
        sync: false
      - key: ENCRYPTION_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: MONGO_URI
        sync: false
